Repository 2021community/Algorithm-skills, pull requests merged in 2021-08, with the labels that each got.

#37 [블록 수정] 자료구조 - 블록의 위키트리 수정 요청 (#30)
  src/data/datastructure.js
Labels: bugfix, block

#41 풀리퀘스트 템플릿에 체크리스트를 추가했습니다.
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#43 [수정] title 재수정(#29)
  index.html
Labels: bugfix

#44 [삭제] 아이콘 삭제(#4)
  src/app.js
Labels: enhancement

#45 [수정] 깃 연결 링크(#9)
  src/app.js
Labels: enhancement

#46 [분류 추가] 코딩 테스트 - 소분류 추가 (#10)
  src/data/codingtest.js
Labels: enhancement
