Repository 2021community/Algorithm-skills, pull requests merged in 2021-09, with the labels that each got.

#52 [분류 삭제] 자료구조 - 이것만은 꼭! 소분류 삭제 (#51)
  src/data/datastructure.js
Labels: enhancement

#55 [리드미 수정] README, blueprint의 제목 및 대분류 수정 (#47)
  README.md
  blueprint.md
Labels: documentation

#54 [수정] Share menu 수정 (#2)
  src/util/open-share.js
Labels: enhancement

#48 [블록 추가] 알고리즘 - 심화 블록들 추가하기 (#13)
  assets/알고리즘/심화/KMP.svg
  assets/알고리즘/심화/기하.svg
  assets/알고리즘/심화/네트워크-플로우.svg
  assets/알고리즘/심화/매니커.svg
  assets/알고리즘/심화/문자열.svg
  assets/알고리즘/심화/백트래킹.svg
  assets/알고리즘/심화/벨만-포드.svg
  assets/알고리즘/심화/세그먼트-트리.svg
  assets/알고리즘/심화/아호-코라식.svg
  assets/알고리즘/심화/이분-매칭.svg
  assets/알고리즘/심화/정수론.svg
  assets/알고리즘/심화/조합론.svg
  assets/알고리즘/심화/최단-경로.svg
  assets/알고리즘/심화/트라이.svg
  assets/알고리즘/심화/플로이드-와셜.svg
  src/data/algorithm.js
Labels: enhancement, block

#59 [수정] - Web Skills FAQ 수정 (#5)
  src/util/open-help.js
Labels: enhancement

#65 [리드미 추가] 코딩 테스트 추가 (#47)
  README.md
Labels: documentation

#70 [리드미 추가] 알고리즘 - 심화, 이것만은 꼭! 추가 (#47)
  README.md
Labels: documentation

#68 [리드미 추가 및 삭제] 자료구조 추가, Contributors 추가, License 삭제 (#47)
  README.md
Labels: documentation

#72 [리드미 추가] 알고리즘 - 기초와 프로그래밍 언어 추가, FAQ 수정 (#47)
  README.md
  blueprint.md
Labels: documentation

#74 [리드미 추가 및 삭제] 목차 추가 및 License 목차 삭제 (#47)
  README.md
Labels: documentation

#80 [블록수정] 리팩토링 - 텍스트 포맷 통합 (#64)
  README.md
  blueprint.md
  src/data/algorithm.js
  src/data/datastructure.js
  src/data/language.js
Labels: refactoring

#86 [수정] 아이콘들의 이름을 소문자로 수정 (#84)
  assets/알고리즘/기초/dp.svg
  assets/알고리즘/심화/kmp.svg
  assets/알고리즘/이것만은-꼭!/bfs.svg
  assets/알고리즘/이것만은-꼭!/dfs.svg
  assets/알고리즘/이것만은-꼭!/dp.svg
  assets/자료구조/심화/avl-트리.svg
  assets/자료구조/심화/b-트리.svg
  assets/자료구조/심화/red-black-트리.svg
  assets/자료구조/심화/방향-비순환-그래프(dag).svg
  assets/코딩-테스트/국내/sw-expert-academy.svg
  assets/프로그래밍-언어/c,-c++.svg
  assets/프로그래밍-언어/c언어.svg
Labels: hotfix

#87 [리드미 수정] 오타 수정 (#83)
  README.md
Labels: hotfix
